
        -- Example: Granting SELECT privilege on a table
        --GRANT SELECT ON schema_name.CUSTOMER TO fpaillao;

        -- Example: Granting EXECUTE privilege on a procedure
        --GRANT EXECUTE ON schema_name.procedure_name TO user_name;

        -- Example: Granting CREATE TABLE privilege
        --GRANT CREATE TABLE TO fpaillao;

create table fpaillao.CUSTOMER (
    id             number generated by default as identity primary key,
    nombre           varchar2(100) not null,
    email          varchar2(100) unique not null,
    rut            varchar2(20) unique not null,
    fechaCumpleanos varchar(100) not null,
    direccion      varchar2(200) not null,
    comuna       varchar2(100) not null,
    region        varchar2(100) not null,
    sexo          varchar2(10) not null
);


INSERT INTO fpaillao.CUSTOMER (id,nombre, rut, direccion, email, comuna, region, fechaCumpleanos, sexo) 
VALUES(1,'Fabian Paillao','15228766-6','cardenal fresno','fpaillao@gmail.com',
'Puente Alto','Metropolitana','21-02-1982','Masculino');

select c1_0.id,c1_0.comuna,c1_0.direccion,c1_0.email,c1_0.fechacumpleanos,c1_0.nombre,c1_0.region,c1_0.rut,c1_0.sexo from customer c1_0;
